twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        color_scheme: 'light dark'
        template:
            default:  'base.html.twig'
        layout:
            default:  'layout/default.html.twig'
    paths:
      'src/Modules/Module/Resource/View/Twig': 'Module'
      'src/Modules/Writing/Article/Resource/View/Twig': 'Article'

when@test:
    twig:
        strict_variables: true
