twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        color_scheme: 'light dark'
    paths:
      'src/Modules/Module/Resource/Twig': 'Module'

when@test:
    twig:
        strict_variables: true
