view_get_all_modules:
    path: /view/all
    controller: App\Modules\Module\Application\Controller\View\GetAllModulesController
    methods: GET 
view_get_module:
    path: /view/{id}
    controller: App\Modules\Module\Application\Controller\View\GetModuleController
    methods: GET 

view_get_all_articles:
    path: /writing/view/all
    controller: App\Modules\Writing\Article\Application\Controller\View\GetAllArticlesController
    methods: GET 
view_get_article:
    path: /writing/view/{id}
    controller: App\Modules\Writing\Article\Application\Controller\View\GetArticleController
    methods: GET 
view_create_article:
    path: /writing/new
    controller: App\Modules\Writing\Article\Application\Controller\View\CreateArticleController
    methods: GET 
view_post_article:
    path: /writing/post
    controller: App\Modules\Writing\Article\Application\Controller\View\PostArticleController
    methods: POST 
