view_get_some_articles:
    path: /writing/{page}
    controller: App\Modules\Writing\Article\Application\Controller\View\GetSomeArticlesController
    methods: GET 
    requirements:
        page: '\d+'
    defaults:
        page: 1
view_get_all_articles:
    path: /writing/view/all
    controller: App\Modules\Writing\Article\Application\Controller\View\GetAllArticlesController
    methods: GET 
view_get_article:
    path: /writing/view/{id}
    controller: App\Modules\Writing\Article\Application\Controller\View\GetArticleController
    methods: GET 
view_create_article:
    path: /writing/new
    controller: App\Modules\Writing\Article\Application\Controller\View\CreateArticleController
    methods: GET|POST 
view_post_article:
    path: /writing/post
    controller: App\Modules\Writing\Article\Application\Controller\View\PostArticleController
    methods: POST 

view_get_category:
    path: /writing/topic/{id}/{page}
    controller: App\Modules\Writing\Article\Application\Controller\View\GetSomeArticlesByCategoryIdController
    methods: GET 
    requirements:
        page: '\d+'
    defaults:
        page: 1
