controllers:
    resource: ../src/Modules/*/Application/Controller/
    type: annotation
    prefix: (_locale)
    requirements:
      _locale: '%app.locales_supported%'
    defaults:
      _locale: '%app.locales_default%'
kernel:
    resource: ../src/Kernel.php
    type: annotation
home:
    path: /
    controller: App\Modules\Module\Application\Controller\GetModuleController
    # if the action is implemented as the __invoke() method of the
    # controller class, you can skip the '::method_name' part:
